### PR TITLE
Add Awk solution for Day 1.

### PR DESCRIPTION
**Pull request by PPKFS**
I'm planning to do each day in a different letter of the alphabet, but here.

### CODE REVIEW

**Comment by PPKFS** [comment]
I'm not sure if you have specific rules as to whether intermediate output is allowed; it's 73 characters but will print out a bunch of extra lines, or 76 if the only line to be printed is the result.

**Comment by Starwort** [comment]
So I don't understand Awk at all, but the rules for the other languages (and I'll leave it to your judgement as to how to best translate them into awk) are essentially:
- The program should be some form of function/lambda/closure/whatever
- The closure can take in a single parameter representing the string of the input (if your language allows reading from stdin more easily than reading a variable that's fine too though)
- The closure should return a value representing the part 1 solution and the part 2 solution (in Python, that's a two-element tuple; in Rust, it's a type implementing `IntoAnswers`, a trait I made to facilitate output from various standard types)
- The runner code can do whatever it wants to get the input into the program and the output out of the program, and is not constrained by characters.
- The measured code size is that of the *expression giving the value*, not any boilerplate required to conform with the IO requirements; for Python, the `lambda i:` at the beginning is *not* counted towards the score; only the expression.

Feel free to write some rules (see Python/README.md and Rust/README.md for examples) that fit the language, ensure your code fits those rules (the IO rules might reduce the character count), and then tag me again once that's done :)

Leaving the PR open for now

**Comment by Starwort** [comment]
Another way to look at it is that the code should be a single expression that you can execute in a REPL (allowing defining a variable that contains the input string first) and gives you a value that is the right answer, but feel free to tweak this to fit Awk better

**Comment by PPKFS** [comment]
I've added a README but...it feels very short :sweat_smile: the runner is just a shell script that calls awk with the `.awk` file and feeds it the file `1.in`.

**Comment by Starwort** [comment]
I've taken a look at Awk's wikipedia page, and I think the rule for Awk will be that input is passed via stdin, and there must be *exactly* one print per solution; please submit your 76-char single-print solution

**Comment by PPKFS** [comment]
Done! I apologise for the horrendous commit history..

**Pull request merged**
